const risk1 = [
  {
    id: 1,
    riesgo: "Riesgo de robo de token para el acceso de cuenta",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 2,
    riesgo: "El tiempo dado es muy escazo para este aplicativo",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 3,
    riesgo: "Un requerimiento dicta que la clave dinamica solo puede cambiar una vez cada dos semanas ",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 4,
    riesgo: "El programador encargado del Fronted es recien graduado de la universidad",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 5,
    riesgo: "El cliente desea que en ningun momento duarante la aplicacion se utilice el signo “$”",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
];
const risk2 = [
  {
    id: 1,
    riesgo: "El libreria que se pidio utiliza para el codigo de barras es muy vieja y puede tener vulnerabilidades",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 2,
    riesgo: "El servidor planeado para este sistema es muy caro y la liquidez del proyecto no es equivalente",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 3,
    riesgo: "Varios empleados presentan problemas de salud debido a un brote de gripa reciente",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 4,
    riesgo: "Existe una falla electrica en las instalaciones lo cual quenera apagones aleatoriamente 1 vez a la semana",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 5,
    riesgo: "El numero de componentes personalizados supera la cifra estinada",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
];
const risk3 = [
  {
    id: 1,
    riesgo: "En el manual tecnico dicta que el nombre del estudiante debe ser la llave primaria",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 2,
    riesgo: "La cantidad de estudiantes dentro de una videoconferencia supera el limite esperado",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 3,
    riesgo: "El servidor s3 (encargado de guardar archivo) varia su precio",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 4,
    riesgo: "Dependencia de internet estable para estudiantes",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 5,
    riesgo: "Riesgo de plagio/copia de evaluaciones",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
];
const risk4 = [
  {
    id: 1,
    riesgo: "Dependencia del proveedor de nube",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 2,
    riesgo: "Riesgo de pérdida de datos durante la migración",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 3,
    riesgo: "El personal interno no está capacitado para la nube",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 4,
    riesgo: "Tiempo de migración mayor al estimado",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
  {
    id: 5,
    riesgo: "Normativas legales de protección de datos",
    categoria: "",
    probabilidad: 0,
    impacto: 0,
    rmmm: "",
  },
];

export default { risk1, risk2, risk3, risk4 };
